### ISSUE TITLE
Call to DynamicMethod failed

### ISSUE THREAD

**Issue by TheOneSock** [jpbruyere/Crow#37]
When following the tutorials, and after adding AddWidget(new Label("Hello World")); to unload. 

I get 
```
{System.NotSupportedException: Wrong MethodAttributes or CallingConventions for DynamicMethod. Only public, static, standard supported
   at System.Reflection.Emit.DynamicMethod.CheckConsistency(MethodAttributes attributes, CallingConventions callingConvention)
   at System.Reflection.Emit.DynamicMethod.Init(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] signature, Type owner, Module m, Boolean skipVisibility, Boolean transparentMethod, StackCrawlMark& stackMark)
   at System.Reflection.Emit.DynamicMethod..ctor(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] parameterTypes, Type owner, Boolean skipVisibility)
   at Crow.GraphicObject.loadDefaultValues() in D:\Programming\aura\Aura\Crow\src\GraphicObjects\GraphicObject.cs:line 760
   at Crow.GraphicObject.Initialize() in D:\Programming\aura\Aura\Crow\src\GraphicObjects\GraphicObject.cs:line 137
   at Crow.GraphicObject.get_CurrentInterface() in D:\Programming\aura\Aura\Crow\src\GraphicObjects\GraphicObject.cs:line 100
   at Crow.GraphicObject.RegisterForLayouting(LayoutingType layoutType) in D:\Programming\aura\Aura\Crow\src\GraphicObjects\GraphicObject.cs:line 971
   at Crow.Interface.AddWidget(GraphicObject g, Boolean isOverlay) in D:\Programming\aura\Aura\Crow\src\Interface.cs:line 595
   at Crow.CrowWindow.AddWidget(GraphicObject g, Int32 interfaceIdx) in D:\Programming\aura\Aura\Aura\CrowWindow.cs:line 190
   at Aura.AuraWindow.OnLoad(EventArgs e) in D:\Programming\aura\Aura\Aura\AuraWindow.cs:line 60
   at OpenTK.GameWindow.OnLoadInternal(EventArgs e)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at OpenTK.GameWindow.Run(Double updateRate)
```

at this line:
```

			dm = new DynamicMethod("dyn_loadDefValues",
				MethodAttributes.Family | MethodAttributes.FamANDAssem | MethodAttributes.NewSlot,
				CallingConventions.Standard,
				typeof(void),new Type[] {CompilerServices.TObject},thisType,true);
```

in GraphicObject.

I see you already had an issue "Windows compilation failed" which I think could be something similar...  as i am on windows and I'm having problems with method attributes.

**Comment by jpbruyere** [comment]
You have to run it with mono, I had the same problem on windows with .net from microsoft.

**Comment by jpbruyere** [comment]
so the steps to get it working under windows:
- install mono following [this link](http://www.mono-project.com/download/#download-win)
- `nuget restore` in the source root.
- build with target framework of mono, 
- run with: `mono Test.exe`

**Comment by jpbruyere** [comment]
crow has been ported to dotnet core, this missing method exception was due to static methods calls vith IL.CallVirt. Mono vm allows it while dotnet vm not. work in progress is in the [xlib branch](https://github.com/jpbruyere/Crow/tree/xlib
